"""destination model added

Revision ID: 727fecc6b7c3
Revises: 6314676aa0b6
Create Date: 2023-09-02 00:36:34.656770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '727fecc6b7c3'
down_revision = '6314676aa0b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('accepted', 'cancelled', name='bookingstatus').create(op.get_bind())
    op.create_table('destination',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destination_id'), 'destination', ['id'], unique=False)
    op.add_column('hotel', sa.Column('destination_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hotel', 'destination', ['destination_id'], ['id'], ondelete='SET NULL')
    op.add_column('hotel_user_booking', sa.Column('booking_status', postgresql.ENUM('accepted', 'cancelled', name='bookingstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotel_user_booking', 'booking_status')
    op.drop_constraint(None, 'hotel', type_='foreignkey')
    op.drop_column('hotel', 'destination_id')
    op.drop_index(op.f('ix_destination_id'), table_name='destination')
    op.drop_table('destination')
    sa.Enum('accepted', 'cancelled', name='bookingstatus').drop(op.get_bind())
    # ### end Alembic commands ###