"""booking_id added to booking model gen

Revision ID: aa7da54c042f
Revises: bd43a48df777
Create Date: 2023-08-27 20:03:10.802776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa7da54c042f'
down_revision = 'bd43a48df777'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel_user_booking',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('available_room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.Date(), nullable=False),
    sa.Column('stopped_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('started_at < stopped_at'),
    sa.ForeignKeyConstraint(['available_room_id'], ['available_room.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('booking_id', 'available_room_id', 'user_id'),
    sa.UniqueConstraint('booking_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hotel_user_booking')
    # ### end Alembic commands ###