"""booking_id added to booking model

Revision ID: bd43a48df777
Revises: dbf372131aae
Create Date: 2023-08-27 19:57:39.605292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd43a48df777'
down_revision = 'dbf372131aae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel_user_booking', sa.Column('booking_id', sa.UUID(), nullable=False))
    op.drop_index('ix_hotel_user_booking_id', table_name='hotel_user_booking')
    op.create_unique_constraint(None, 'hotel_user_booking', ['booking_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hotel_user_booking', type_='unique')
    op.create_index('ix_hotel_user_booking_id', 'hotel_user_booking', ['id'], unique=False)
    op.drop_column('hotel_user_booking', 'booking_id')
    # ### end Alembic commands ###