"""Regenerate HotelMedia

Revision ID: c017a2514447
Revises: 87e3722207df
Create Date: 2023-08-27 16:55:34.434619

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c017a2514447'
down_revision = '87e3722207df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_hotel_media',
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('hotel_id', 'media_id')
    )
    op.drop_index('ix_hotel_media_id', table_name='hotel_media')
    op.drop_table('hotel_media')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel_media',
    sa.Column('hotel_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('media_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], name='hotel_media_hotel_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name='hotel_media_media_id_fkey'),
    sa.PrimaryKeyConstraint('hotel_id', 'media_id', 'id', name='hotel_media_pkey')
    )
    op.create_index('ix_hotel_media_id', 'hotel_media', ['id'], unique=False)
    op.drop_table('link_hotel_media')
    # ### end Alembic commands ###