"""unique columns added to hotelrating

Revision ID: dbf372131aae
Revises: c017a2514447
Create Date: 2023-08-27 18:53:36.955352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf372131aae'
down_revision = 'c017a2514447'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'hotel_rating', ['hotel_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hotel_rating', type_='unique')
    # ### end Alembic commands ###